require 'rails_helper'

RSpec.describe "Pigments", type: :request do
  describe "GET /pigments" do
    it "works! (now write some real specs)" do
      get pigments_path
      expect(response).to have_http_status(200)
    end
  end
  
#(COPIED from physical_colors_spec)  from autogenerated controller spec (by scaffold, was deleted in spec/controllers)

  # This should return the minimal set of attributes required to create a valid
  # Pigment. As you add validations to Pigment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'Pigment 1'}
  }

  let(:invalid_attributes) {
    {name: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PigmentsController. Be sure to keep this updated too.
  let(:valid_session) { {user_id: 1} }

  describe "GET #index" do
    it "returns a success response" do
      pigment = Pigment.create! valid_attributes
      get url_for(controller: :pigments, action: :index)
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      pigment = Pigment.create! valid_attributes
      get url_for(controller: :pigments, action: :show, id: pigment.to_param)
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Pigment" do
        expect {
          post url_for(controller: :pigments, action: :create, pigment: valid_attributes)
        }.to change(Pigment, :count).by(1)
      end

      it "renders a JSON response with the new pigment" do

        post url_for(controller: :pigments, action: :create, pigment: valid_attributes)
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(pigment_url(Pigment.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new pigment" do
        post url_for(controller: :pigments, action: :create, pigment: invalid_attributes)
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'Pigment 456'}
      }

      it "updates the requested pigment" do
        pigment = Pigment.create! valid_attributes
        put url_for(controller: :pigments, action: :update, id: pigment.to_param, pigment: new_attributes)        
        pigment.reload
        new_attributes.each do |attribute, value|
          expect(pigment.send(attribute)).to eq(value)
        end
      end

      it "renders a JSON response with the pigment" do
        pigment = Pigment.create! valid_attributes
        put url_for(controller: :pigments, action: :update, id: pigment.to_param, pigment: valid_attributes)        
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the pigment" do
        pigment = Pigment.create! valid_attributes
        put url_for(controller: :pigments, action: :update, id: pigment.to_param, pigment: invalid_attributes)
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested pigment" do
      pigment = Pigment.create! valid_attributes
      expect {
        delete url_for(controller: :pigments, action: :destroy, id: pigment.to_param)
      }.to change(Pigment, :count).by(-1)
    end
  end
  
end
