require 'rails_helper'

RSpec.describe "WhiteBases", type: :request do
  describe "GET /white_bases" do
    it "works! (now write some real specs)" do
      get white_bases_path
      expect(response).to have_http_status(200)
    end
  end
  
#(COPIED from physical_colors_spec)  from autogenerated controller spec (by scaffold, was deleted in spec/controllers)

  # This should return the minimal set of attributes required to create a valid
  # WhiteBase. As you add validations to WhiteBase, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'WhiteBase 1'}
  }

  let(:invalid_attributes) {
    {name: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WhiteBasesController. Be sure to keep this updated too.
  let(:valid_session) { {user_id: 1} }

  describe "GET #index" do
    it "returns a success response" do
      white_base = WhiteBase.create! valid_attributes
      get url_for(controller: :white_bases, action: :index)
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      white_base = WhiteBase.create! valid_attributes
      get url_for(controller: :white_bases, action: :show, id: white_base.to_param)
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WhiteBase" do
        expect {
          post url_for(controller: :white_bases, action: :create, white_base: valid_attributes)
        }.to change(WhiteBase, :count).by(1)
      end

      it "renders a JSON response with the new white_base" do

        post url_for(controller: :white_bases, action: :create, white_base: valid_attributes)
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(white_basis_url(WhiteBase.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new white_base" do
        post url_for(controller: :white_bases, action: :create, white_base: invalid_attributes)
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'WhiteBase 456'}
      }

      it "updates the requested white_base" do
        white_base = WhiteBase.create! valid_attributes
        put url_for(controller: :white_bases, action: :update, id: white_base.to_param, white_base: new_attributes)        
        white_base.reload
        new_attributes.each do |attribute, value|
          expect(white_base.send(attribute)).to eq(value)
        end
      end

      it "renders a JSON response with the white_base" do
        white_base = WhiteBase.create! valid_attributes
        put url_for(controller: :white_bases, action: :update, id: white_base.to_param, white_base: valid_attributes)        
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the white_base" do
        white_base = WhiteBase.create! valid_attributes
        put url_for(controller: :white_bases, action: :update, id: white_base.to_param, white_base: invalid_attributes)
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested white_base" do
      white_base = WhiteBase.create! valid_attributes
      expect {
        delete url_for(controller: :white_bases, action: :destroy, id: white_base.to_param)
      }.to change(WhiteBase, :count).by(-1)
    end
  end
  
end
